export class IconUtil {
  static readonly APP_ICON: string = 'https://img.icons8.com/fluency/240/school-building.png';
  static readonly ARROW_LEFT: string = 'https://img.icons8.com/fluency-systems-filled/96/left.png';
  static readonly ARROW_RIGHT: string = 'https://img.icons8.com/fluency-systems-filled/96/chevron-right.png';
  static readonly PERSON: string = 'https://img.icons8.com/fluency-systems-filled/96/user.png';
  static readonly ADD: string = 'https://img.icons8.com/fluency-systems-filled/96/plus-math.png';
  static readonly EMPTY: string = 'https://img.icons8.com/fluency-systems-filled/96/nothing-found.png';
  static readonly DELETE: string = 'https://img.icons8.com/fluency-systems-filled/96/trash.png';
  static readonly COMMUNITY: string = 'https://img.icons8.com/fluency-systems-filled/96/groups.png';
  static readonly TIME: string = 'https://img.icons8.com/fluency-systems-filled/96/clock.png';
  static readonly LOCATION: string = 'https://img.icons8.com/fluency-systems-filled/96/marker.png';
  static readonly HOME: string = 'https://img.icons8.com/fluency-systems-filled/96/home.png';
  static readonly CONTACTS: string = 'https://img.icons8.com/fluency-systems-filled/96/conference-call.png';
  static readonly CALENDAR: string = 'https://img.icons8.com/fluency-systems-filled/96/calendar.png';
  static readonly LIST: string = 'https://img.icons8.com/fluency-systems-filled/96/bulleted-list.png';
  static readonly SETTINGS: string = 'https://img.icons8.com/fluency-systems-filled/96/settings.png';
  static readonly WALLET: string = 'https://img.icons8.com/fluency-systems-filled/96/wallet.png';
  static readonly OK: string = 'https://img.icons8.com/fluency-systems-filled/96/checkmark.png';
  static readonly STATISTICS: string = 'https://img.icons8.com/fluency-systems-filled/96/combo-chart.png';
  static readonly INFO: string = 'https://img.icons8.com/fluency-systems-filled/96/info.png';
  static readonly SEARCH: string = 'https://img.icons8.com/fluency-systems-filled/96/search.png';
  static readonly INPUT: string = 'https://img.icons8.com/fluency-systems-filled/96/edit.png';
  static readonly LOCK: string = 'https://img.icons8.com/fluency-systems-filled/96/lock-2.png';
  static readonly CANCEL: string = 'https://img.icons8.com/fluency-systems-filled/96/cancel.png';
}